"""update db

Revision ID: 01f14063ec17
Revises: ec463615be2d
Create Date: 2016-05-03 10:56:42.879576

"""

# revision identifiers, used by Alembic.
revision = '01f14063ec17'
down_revision = 'ec463615be2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uitask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cport', sa.Integer(), nullable=False),
    sa.Column('bport', sa.Integer(), nullable=True),
    sa.Column('logpath', sa.String(length=64), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cport', 'uid', 'status')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uitask')
    ### end Alembic commands ###
